language: node_js
node_js:
  - node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: jrg/3OBiLuXBj6fV1BU+Ql2jUMirVae/luyv6xqKn2tvpJnP1bTEzMXZl23WoDQ4x6refNgtYfpf21t141w4JFYbMWsbQ8Ty1SHynHGwgJnLG7Y8O0TD8NkawWZMXDs4gak3oRGoOqMlPMg3OWxDtGHI4m5yMN3izRg/R+rH3M1W1WhkGOFHRdREEd3PD1mFef0vLzezhJnTyP1vOljH7B6KoB3nY4cNnV6gKKJsv6Dncc9VVtIxcK2Jz1HOs8/BRv6YP0iH4LRcEVCx1qGAdr+6AlduRgIhS2GoiIFbXKy1lXSXdjOlVunOPUpyAwHbUW2J82xBzmRgpB8dNKPq94tccsRKsSLKC1XZc/LvzoZJv4hzMQk0prQE1/Nc6v4AityFTtWPfc0cvjyNs9DdKsTA10e+5Hmvoar1njF9Kqz/vSvv2Q2FPIeAKYdvKj5rNYbWckIJ6TTq79GjH81jMUZLYu9ZHNhRQSfoyC6GxTFNZHyyRI7msAyc5RnNtkJ3rm8o1reSp/piVo67leEayk2vbB7HXGsp4yVISOS0MFty4Pbhe+IaXpd2u17qK0+vDLmRE4r9hnAzdvSQGVzjWMO2JuTmsVXfo7G9cbLPtZtR2/fELNOGpX1IhDyNxtAwkGW0Ou62igfST+lFon+L/pjd6GZK6bT2F19SsnEL6Mc=
  app: bit-poll
  skip_cleanup: true
