language: node_js
node_js:
  - node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Qk4ho/S5fI7G1s0jFnvYZ2wqrUNVNbIT6gad+oeljSuZOviuveJJtnDotG1C1AGiH3Mplli1qSe1SHpccJPk0I/DYXx9kUQ4tOSzVl3rlYG3q3+SkQhroW9MtPt/kCZz4Fxon/PzThZfvI8wgN3xUDay25Znz84Uav3Q31/hERcXESfwBYYhrID/P5takoMsowRuqu7PLr1VYORqwhreDfilTI3ujbCVORmh+py0rGK3+sEUjTC4N5KWeQTwarvOxdg1EPwKm3uBlcBB6Ck0cPS2l//eUrMaIereU/TDfDr/CPtxGkGVsQHdx9LTLY4yCSyvZMIEEtwBic4MBTMT5+Xr6vEzB8ojRPtFvBepJ4MvOE05a/4/C+1yvl9LOdFveRNr6X/SFryVv++w7boCjzLmUyuoOVeZmSUEeX3TyGmvO2ws/V5LK+eRqO0C24EGTRSejk9wIgWjcB+5tNcpnVJxZ3NoshuTbMLUw/w+AdyBlCWgZnY8cjd61eF4XbDKGM7VeDtZP5xdNb+6YD6rPgmFZXnluNiVHP2jrt1FQiS7IBPp+mqiUP/ApH94qN9MAMBrIfTRFGgh3LCO8jxBa8YmDEPfbdhTcsnyNSf6TMNI1Yj4bJ11Td1LmG6YSqwSwV4rWur0reA3WIJfUsFyY+NEP0cTyA437ahkX/qB5UA=
  app: bit-poll
  skip_cleanup: true
