language: node_js
node_js: '10'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ncICVimK55WPvU9GhRQaAOuWuSlczWzPHHirOyTOkm54qekPAa72zotud8iaChn6mO+XKtaF0Vd+GRRGp0L8XQzRX/OPzfJ8ghOS59ze32muTkm9+Tyvq2PKoZUkfpvcu4jI05qW8l7YZD5W3fpOhRsaQEVXKEt1hQ1hbqzoCoKw6nMNgGzuBQ0jOuIls5pFnZwDmqXeaUxQsVz69QPdxP1YtNfa9q48F58bWo2WrJ9zUwjw97Ls24KxwrDQPgMIJe+TOAJqydbiRJmav/01CjcHGGdhSwKCtCoZyI+pzhgEeGX2evltLxFetQNFuBiW4d0NJBhGx7l/8Nw30Vwgaind9z8lef8Q+2/QW4I0sgADe34ZPFt4wbETAn/z6kBl0vuthyW7sd/mWbmbfCmJhz9y6D61Zvj+rUBUTX1Fi7wCOg6COwk1Lr6br+7nTtRDLOvf4danXvCUlWkcaRdZv5jAbkeW+Gk9dgjTxSXOWvht/8xP265HLIleyO4Lu3DTbt9thhA20hpC1jVVkSctQK3Cfe66EeMiontnv7SMEcD3qadksDvHFIb0adbZeEripsigwnGFgo3MSJQI7rz280vQEOwynTlbTxNhyucH4prnLC9yqTf/QEE3tZgD8+/Pg+Owff2XQF6RbwrLQ2T9WFwoKPOIJysUW7Jy6EYmIig=
  app: bitpoll
  skip_cleanup: true
