language: node_js
node_js:
  - node
notifications:
  email: false
deploy:
  api_key:
    secure: qN7ykYRef+WGkm9BUa81YAvISRbcB6kSFdyID4eNFSxEFKJKtjbN1GIfH3T4/gzTRevVfgDRJG6yyBaVk2noxjdj3YjFtc8XHs9M3km9kzoq0RybmaVABrC3OE1HzRYRpenLiSkWsyA8pFjsL6J9oZCvaMEhXq3fhUHAcqpcH5j5KbyKvYDKekjPsu8T9X+t9fVXDHms+sWKf4eoHy7S7EFEOJe1JXV+SKmo38mRbeZHpB/I6USpAoIQSEuPmUuvNgCOAzVMcTMQdtgPi4UYlxTciaSaHot5VOxcKOVXg/qbOrUX6EaqFkRmsKHqkb9NeZE47xUScEKBXdbQ5Zar5/ZByfRcH2S79xHH26bfvEuTkQPTQz79TMAIuoYlphp0AbSEZMF4YRjKLP4VSzD6/EqOOPnTPj9+TzLfimzggQGaMTokFF1Gs0oDDvB/TWYPO3YLPnD9GtqDJiZKb87eJJdlDLQDIY5W+TKVB1qR8EnvvkRTCBe8c3qvYR66O89Mr4aR6efCWp12IXei6049EkSYhtG1tz6pQ0TCUrLZEPD7G1iqU8S0fiXW3tpOWUZXoqRqojeSrrSFfIEwLh+HbPLdFsJrkZrYoXHqAwYDlQ+QC4Zq+AGiYkulpJs9STG+Lhf2tmKOlhDDhzrjCXtIWteLOU4zj7QohSFDfm5Rclc=
  app: bit-poll
  skip_cleanup: true
